ERR_UNKNOWNERROR: Fix compat with Elixir 1.12
1. the error is different, which made the test fail
2. it contains a newline, which caused a protocol error